/**
 * @license Copyright (c) 2003-2012, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.html or http://ckeditor.com/license
 */

CKEDITOR.plugins.add( 'template', {
	requires: 'dialog',
	lang: 'en,ja,ko,zh,zh-cn', // %REMOVE_LINE_CORE%
	icons: 'template', // %REMOVE_LINE_CORE%
	init: function( editor ) {
		//editor.addCommand( 'template', new CKEDITOR.dialogCommand( 'template' ) );
		/*editor.addCommand( 'template', {
			// Define the function that will be fired when the command is executed.
			exec: function( editor ) {
				window.open('/mail/popup/template/list.do','templateWin','toolbar=no,width=720,height=600,top=0,left=0;directories=no,status=no,scrollbars=yes,resizable=no,menubar=no');
			}
		});
		editor.ui.addButton && editor.ui.addButton( 'Template', {
			label: editor.lang.template.toolbar,
			command: 'template',
			toolbar: 'inserts'
		});*/
		editor.addCommand( 'template', {
			// Define the function that will be fired when the command is executed.
			exec: function( editor ) {
				//window.open(app.contextPath + '/mail/popup/template/list.do','templateWin','toolbar=no,width=720,height=600,top=0,left=0;directories=no,status=no,scrollbars=yes,resizable=no,menubar=no');
				// 편지지 레이어 숨김
				EditorTemplatePlugin.open();
			}
		});
		editor.ui.addButton && editor.ui.addButton( 'Template', {
			label: editor.lang.template.toolbar,
			command: 'template',
			toolbar: 'inserts,'+ 6
		});
		
		//CKEDITOR.dialog.add( 'template', this.path + 'dialogs/template.js' );
	}
});


/**
 * The number of columns to be generated by the smilies matrix.
 *
 *		config.smiley_columns = 6;
 *
 * @since 3.3.2
 * @cfg {Number} [smiley_columns=8]
 * @member CKEDITOR.config
 */
