/**
 * @license Copyright (c) 2003-2012, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.html or http://ckeditor.com/license
 */

CKEDITOR.plugins.add( 'images', {
	requires: 'template',
	lang: 'en,ja,ko,zh,zh-cn', // %REMOVE_LINE_CORE%
	icons: 'images', // %REMOVE_LINE_CORE%
	title: '이미지',
	init: function( editor ) {
		editor.addCommand( 'images', {
			// Define the function that will be fired when the command is executed.
			exec: function( editor ) {
                EditorImagePlugin.open();
			}
		});
		editor.ui.addButton && editor.ui.addButton( 'Images', {
			label: editor.lang.images.toolbar,
			command: 'images',
			toolbar: 'inserts,'+ 7
		});
		//CKEDITOR.dialog.add( 'template', this.path + 'dialogs/template.js' );
	}
});


/**
 * The number of columns to be generated by the smilies matrix.
 *
 *		config.smiley_columns = 6;
 *
 * @since 3.3.2
 * @cfg {Number} [smiley_columns=8]
 * @member CKEDITOR.config
 */
